### ISSUE TITLE
Erro ao tentar fazer deploy do unleash

### ISSUE THREAD

**Issue by eulercb** [MP-ES/k8s-deploy#22]
![image](https://user-images.githubusercontent.com/12671634/136268454-275ce16c-d8e3-4acc-8275-e7dbe95e630e.png)
https://github.com/MP-ES/unleash-gampes/runs/3819284617

```
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on:
      - self-hosted
      - mpes
      - linux
    steps:
      - uses: AutoModality/action-clean@v1
      - uses: actions/checkout@v2
        with:
          path: source
      - uses: MP-ES/k8s-deploy@v1
        env:
          base64_kubeconfig_dev: ${{ secrets.base64_kubeconfig_dev }}
        with:
          k8s-envs: |
            dev
          gitops-token: ${{ secrets.REPO_MANAGER_ROSE_PAT }}
          manifest-dir: source/kubernetes
      - if: always()
        run: |
          rm -rf source
          docker ps -q | xargs -n 1 -P 8 -I {} docker stop {}
```
